### ISSUE TITLE
Using list pair whisper component will make OliveHelps crash

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#136]
Using list pair whisper component will make OliveHelps crash.
```javascript
await whisperService.create({
      label: 'List pair',
      components: [
        {
          type: whisperService.WhisperComponentType.Markdown,
          body: 'This is a "list pair" component without box. ',
        },
        {
          type: whisperService.WhisperComponentType.ListPair,
          lable: 'label',
          value: 'style none + copable false',
          style: whisperService.Urgency.None,
          copyable: false,
        },
      ],
      onClose: () => {},
    });
```
OliveHelps will crash after running the code above in a loop.
LDK version: 3.0.0-beta.1
OliveHelps version: 0.16.2

**Comment by cshields-oliveai** [comment]
We have opened a new LDK ticket to investigate and resolve: SIDE-2187.
As with other your other reported issues, we will provide updates in this issue as we work to get it resolved, and will provide a pull request link if any work touches the LDK for your reference.

**Comment by BrettMugglinOlive** [comment]
So, I believe I may have identified the problem, but just want to confirm that it is really the issue.

In the sample code you provided, one of the attributes for the ListPair seems to be misspelled as `lable` when it should be `label`. After making that change I had no problems running that code.

Let us know if that turns out to be the issue!

**Comment by hans-hsieh-asus** [comment]
Thank you. After fixing the incorrect `lable`, it's working now.
