### ISSUE TITLE
Different line-height for Box and CollapseBox

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#205]
We want to show a list of items in a whisper. To prevent making the whisper too long, we want to show only the first 5 items by default, and the user can click "more" to expand the remaining 5 items.
We tried to implement it by putting the remaining 5 items in a `CollapseBox`. And the view looks like:
![image](https://user-images.githubusercontent.com/68371064/120072161-ee5b0e80-c0c4-11eb-881b-3b1a05e199f8.png)
(Each item is implemented by one `CheckBox`, two `Message`, and a `Divider`.)
The line-height looks too large.
We tried to put the first 5 items in a `Box`, and it looks better now.
![image](https://user-images.githubusercontent.com/68371064/120072153-e26f4c80-c0c4-11eb-9a7e-955c5514270c.png)
However, when we expand the remaining 5 items, you can see that the line height for the first 5 items and the remaining 5 are different:
![image](https://user-images.githubusercontent.com/68371064/120072437-80afe200-c0c6-11eb-997f-0fe622db908c.png)
Any suggestion to make it look better?

**Comment by DanielWagersOlive** [comment]
Thank you for the question!  We'll take a look and report back.

**Comment by cshields-oliveai** [comment]
@hans-hsieh-asus - This seems like an issue with rendering line height when a `CollapseBox` is expanded, will will have to investigate further on that one. We will create an internal task for that.

I wanted to recommend a few things though that may help your specific use case:
First, `RadioGroup` and `Checkbox` components now support Markdown. Instead of composing those options with `Checkbox` and two messages perhaps you could use one `Checkbox` component with provided markdown label to achieve the same thing.

The other idea that comes to mind is to leverage the new Whisper update mechanism to batch results instead of a `CollapseBox`. You could include a button with on `onClick` that updates the existing Whisper, simulating pagination.

Let us know if any of these points help with your design.

**Comment by hans-hsieh-asus** [comment]
Thanks. Putting the description and probability into the label of the checkbox can partially solve the problem.
However, the gap between the divider and the checkbox is still different.
We tried to use link and button to implement our own "more"-like functionality. But based on the look-and-feel, we decided to still use the built-in `CollapseBox` for now. Therefore, there're two things we hope to have a better solution:
1. The gap between the components that are in `CollapseBox` is different from the gap above the `CollapseBox`
![gap](https://user-images.githubusercontent.com/68371064/120971107-dbb89780-c79e-11eb-8cc2-372c86998d38.jpg)
1. The gap around the divider is a little too wide.

For now, we will use `CollapseBox`. It's not a blocking issue for us.

**Comment by cshields-oliveai** [comment]
@hans-hsieh-asus We have created an internal issue for this: SIDE-2466. We will let you know when it's resolved.

**Comment by CandiceCLB** [comment]
Updating card number: HELPS-279.

**Comment by CandiceCLB** [comment]
This issue has been resolved with the latest OH release, V0.20.0
