### ISSUE TITLE
File disappears from Dropzone after dragging and dropping file if the Dropzone is specified as a child of a Box

### ISSUE THREAD

**Issue by IanKrieger** [open-olive/loop-development-kit#342]
After dragging and dropping a file into the Dropzone, the file disappears from view. Noticed this when specifying the Dropzone as a child of a `Box` component.

Steps to reproduce:
 - Create Dropzone as a child of a Box
 - Drag a file into it
 - Wait 5 seconds - 2 minutes to see it disappear visually, as well as programmatically.

https://user-images.githubusercontent.com/48930920/133312379-ead98b07-ed1b-45d9-93e5-7d79b09e7b54.mov

**Comment by MaggieMaSS** [comment]
Hey @IanKrieger , sorry for the late reply! I tried to reproduce this defect issue but I didn't see that file disappears in 5 s - 2 min. I think this issue has been properly solved, but could you please double check to see if this issue still persists? If this issue is still there, could you please send me code snippet? Thanks!

**Comment by BrettMugglinOlive** [comment]
I'm going to go ahead and close this thread for now. If this is still an issue for you, please feel free to reopen this and provide a code snippet as @MaggieMaSS requested. Thanks!
