### ISSUE TITLE
[Feature Request]: CollapseBox preview

### ISSUE THREAD

**Issue by kingofclarkston** [open-olive/loop-development-kit#367]
We would like to be able to preview the box contents when the box is minimized. Thanks!
<img width="398" alt="Screen Shot 2021-09-28 at 12 56 10 PM" src="https://user-images.githubusercontent.com/62415389/135133131-c20d0f6e-a599-4538-a773-7223f2c061de.png">

**Comment by BrettMugglinOlive** [comment]
Ok, maybe the solution would be to add a `preview` attribute or something like that to the `CollapseBox` so that when configured it would show x number of components, with the faded area shown in the screen shot at the bottom when the Collapse Box is closed. But, this is speculative, and we will have to talk through it internally.

I created HELPS-2398 to track this issue.

**Comment by MaggieMaSS** [comment]
This feature has been released on Olive Helps 0.36.3 and LDK v3.16.0. 

It's done and I'm closing this issue!
