### ISSUE TITLE
Icon with onClick doesn't have clickable indicator

### ISSUE THREAD

**Issue by AlyseTack** [open-olive/loop-development-kit#409]
We'd like to have the cursor to change to "pointer" or possibly have an additional indicator of the ability to click when we have an onClick action defined as it's hard to tell when an icon is clickable.

Example screen:
![image](https://user-images.githubusercontent.com/14366837/140438117-1b678320-5184-4c9b-8a77-6b49af074435.png)

**Comment by BrettMugglinOlive** [comment]
Absolutely, if there is an onClick handler given, we should be showing a pointer! But I don't know if it's clear from your screenshot what component is at fault here. Could you provide some more details?

**Comment by AlyseTack** [comment]
The component is the Icon component and in this picture it's the back arrow to the left of "James Kelly"

**Comment by AlyseTack** [comment]
We don't have the loop in the library yet but I can either send the loop.js or the full component code.

Here's the component configuration we are using:
```
<oh-icon
  key="back-arrow-button"
  name="arrow_back_ios"
  size={IconSize.Medium}
  color={Color.Black}
  onClick={() => dispatch(updatePageFunction())}
/>
```

We are using `"@oliveai/ldk": "3.5.1"`

**Comment by BrettMugglinOlive** [comment]
Ok, so I looked at this a little closer. I was confused, cause it seemed like the test we have for this is/was passing, as a pointer appears on the `Icons` with an `onClick` in the self test `Whisper Aptitude -> Icon Rendering`. But I realized that the reason why this was passing wasn't because of the presence of the `onClick`, but rather the presence of the `tooltip` attribute. Obviously, this shouldn't always be the case, so I created HELPS-2390 to track this issue.

But, on the bright side, as a workaround add a `tooltip` to your Icon, and it will have a pointer when hovering over it! And then you can adjust once we address this issue.

**Comment by AlyseTack** [comment]
@BrettMugglinOlive Thanks so much for looking into this!  I'll go ahead and add a tooltip in the meantime

**Comment by BrettMugglinOlive** [comment]
This bugfix has been released! Closing this thread
