### ISSUE TITLE
Incorrect onSelect behavior with Autocomplete component

### ISSUE THREAD

**Issue by kyuhas** [open-olive/loop-development-kit#418]
Hi all. I was trying to use the Autocomplete component (see code below) and noticed that even though the `val` variable in onSelect is typed as an array of strings, it is actually a string. 

```
        <oh-autocomplete
          key="zip-auto-filter"
          label="Zip code"
          multiple={false}
          options={ZIP_AUTOCOMPLETE_OPTIONS}
          onSelect={(_, val) => {
            console.log(val);
            console.log(typeof(val));
          }}
        />
```

For example, one of my options for the autocomplete was `{"label":"10940","value":"10940"}`, but when I selected that option, the logs would show up as: 

```
2021-11-10T13:15:12-05:00 INF ["10940"] routine.group=main routine.label=app.Run routine.name=app.Run.e5023018-731b-40ed-98da-e5f3f6c36b69 sentry=false
2021-11-10T13:15:12-05:00 INF string routine.group=main routine.label=app.Run routine.name=app.Run.e5023018-731b-40ed-98da-e5f3f6c36b69 sentry=false
```

So the `val` is actually a string, but typed as a string array. This is causing problems for me where I can't actually select any of the options.

**Comment by MaggieMaSS** [comment]
Hey @kyuhas  Thanks for your feedback! We have created a ticket in OliveHelps to better address this issue.  We appreciate your feedback and will let you know when it's gonna fixed. Thanks!

**Comment by BrettMugglinOlive** [comment]
Ticket number is HELPS-2221.

**Comment by MaggieMaSS** [comment]
Did couple of tests about this issue, we found that it’s returning object right now instead of array or string. This ticket was created last November and we noticed there’s changes regarding the type of AutocompleteOption in this PR [Merge pull request #491 from open-olive/bugfix/HELPS-3058 · open-olive/loop-development-kit@4ba8cba](https://github.com/open-olive/loop-development-kit/commit/4ba8cbab7ce0cf399aad28016568529ec99e496d) onSelect takes array of AutocompleteOption's value as augment and it’s returning object right now. Right now we have the workable version even though the type is not  array. I don’t think this is a bug anymore. But to double check,  could you please let us know that if this is still a blocker for you

**Comment by kyuhas** [comment]
I had to modify my code with the newest LDK version to accept an object now instead of a stringified list, but it's still the same problem I faced before, just an object instead of a string. This isn't blocking me because I have a workaround, but until the type matches the function declaration (onSelect: WhisperHandlerWithParam<string[]>;), it seems like it's still a bug.

**Comment by MaggieMaSS** [comment]
@kyuhas  Thanks for the reply. We will work on matching the function declaration and type. And we'll keep you updated!

**Comment by MaggieMaSS** [comment]
![Screen Shot 2022-02-15 at 4 41 45 PM](https://user-images.githubusercontent.com/84045424/154158087-5f20a0e2-4c25-445e-beeb-118b8592d2be.png)
@kyuhas  An array is considered as an “object” if you use JavaScript’s typeof function,    I  used Array.isArray(). and its returning value is true, which means this value is an array.    There might be some confusion here due to the definition of the `typeof` function.        
```
onSelect: (error, value, onSelectWhisper) => {
              console.log('typeof onSelect: ', typeof value);
              console.log('array.isArray of value:', Array.isArray(value));
              }
```

**Comment by MaggieMaSS** [comment]
@kyuhas If the reply above makes sense, do you think I can go ahead and close this issue?  😸

**Comment by kyuhas** [comment]
Hi @MaggieMaSS yes, you can close this, thanks!
