### ISSUE TITLE
Background option on the box component

### ISSUE THREAD

**Issue by AlyseTack** [open-olive/loop-development-kit#428]
We would like to have the option of adding a background to a box component so we can have a line of text and a button grouped together with the same background color as seen below.

![image](https://user-images.githubusercontent.com/14366837/142334959-19d84075-c16f-4868-92ed-3e669eca1e7f.png)

**Comment by MichaelOliveMcCarrick** [comment]
I've gone ahead and created HELPS-2324 to track this request.

**Comment by BrettMugglinOlive** [comment]
HI @AlyseTack! So, the good news is that we are going to address this!...Eventually :) Our roadmap includes adding the ability for loop authors to theme their Loop / Whispers with non Olive colors, and that work should encompass this.

Rather than creating a one off solution for this request, we've decided to just roll this into that work. So, I'm going to close this thread for now, but it is on our radar! Even though it's marked as "Wontfix", it will be addressed.
