### ISSUE TITLE
Alignment and spacing broken after LDK v3.10.0 and OH v0.30.2 new release

### ISSUE THREAD

**Issue by alobaidizt** [open-olive/loop-development-kit#493]
We have a loop on the library **Circulo Network Provider** that has experience some changes in UI after the new release of OH version 3.10.0. Please see the screenshots below showing how the main loop whisper looked before the update and after.

<img width="383" alt="network-provider-before" src="https://user-images.githubusercontent.com/5909460/150368328-ed7d7d4e-5dec-4f6a-9964-f2819181b399.png">

![network-provider-after](https://user-images.githubusercontent.com/5909460/150368340-b43f025c-1377-4bf7-9f70-bd2af4fed3d3.png)

#### To reproduce:
- Open the loop in OH v0.30.2 vs opening it in OH v0.29.4

**Comment by JosefBud-olive** [comment]
Thank you for reporting this, @alobaidizt! I've asked someone on our UI team to look into this and will follow up here later today

**Comment by JosefBud-olive** [comment]
This issue is being tracked on our end in [HELPS-3083](https://crosschx.atlassian.net/browse/HELPS-3083) and the fix is already in code review.

**Comment by BryanStoner-Olive** [comment]
Heya @alobaidizt! We've recently made some updates to the `message` component to better reflect our internal designs and to help increase the legibility. 

To fix the bug you've encountered here, we removed the `minHeight` from the `message` component so you should see your layout for the most part restored. The other spacing change is related to an increase in `lineHeight` for when titles/captions of the `message` component span more than 1 line.

To get a little closer to the original design, you could combine the `message` components together and have 1 `message` component for both the title and caption rather than 2 separate `message` components. 

If you think that won't work let us know and we can come up with an alternative solution!

**Comment by alobaidizt** [comment]
I think it looks much better now. Can't spot the difference. Will follow up if there's any further action required from Olive Helps. For now, I'll consider this issue resolved and close this issue. Thank you for the resolution!
