### ISSUE TITLE
Loading loop on user login to Olive Helps

### ISSUE THREAD

**Issue by alobaidizt** [open-olive/loop-development-kit#494]
Attempting to load the loop on user login to Olive Helps leads to two whispers created when the user downloads the loop from the library. After that, the loop loads up on user login just fine, without creating 2 whispers.

The issue is the loading of two whispers when user downloads the loop.

To reproduce:
- Create a whisper in the main index file of the loop src outside of loopOpenHandler and search listeners.
- Create/install the loop on Olive Helps. You should see two whispers loaded into Olive Helps sidebar.

**Comment by alobaidizt** [comment]
@JosefBud-olive Here's a snippet showing the code that causes this case:

```
(async () => {
  
  startSearchListener(onSearchEvent);
  
  WhisperFactory.createDefaultBloodPressureWhisper();
  ui.loopOpenHandler(() => {
    WhisperFactory.createDefaultBloodPressureWhisper();
  });
})();

```

**Comment by alobaidizt** [comment]
Here's the visual for the issue as well.

![loadin-two-whispers-on-download](https://user-images.githubusercontent.com/5909460/150403062-ddf0317f-2e57-4ec6-bc95-e576ee17c2b1.gif)

**Comment by JosefBud-olive** [comment]
Thank you for reporting this, @alobaidizt! I was able to recreate this on my end and sent a ticket over to the appropriate team. It's tracked on our end in [HELPS-3102](https://crosschx.atlassian.net/browse/HELPS-3102).

**Comment by JosefBud-olive** [comment]
Hey there @alobaidizt! I forwarded this ticket to our Core team who informed me that this is expected functionality. The `loopOpenHandler` callback will execute when selecting the loop from the dropdown as well as on install/restart/unpause, but not on login. I believe the intention is to prevent end users from being inundated with several start whispers from every installed loop when they log in. We'll be updating our documentation today to mention this behavior so that this doesn't cause confusion in the future.
