### ISSUE TITLE
CustomHeight no longer being honored OH v0.30.2 LDK 3.10.1

### ISSUE THREAD

**Issue by IanKrieger** [open-olive/loop-development-kit#501]
Had a few `<oh-box> ...` elements using `CustomHeight` param.

On update to new version of OH, the custom height param seems to no longer be honored, and downgrading does not fix.

### Before
<img width="401" alt="Screen Shot 2022-01-18 at 2 43 52 PM" src="https://user-images.githubusercontent.com/48930920/151017872-1a39f7b3-a718-4b00-adae-c42e3e82a9aa.png">

### After
<img width="395" alt="Screen Shot 2022-01-21 at 10 22 27 AM" src="https://user-images.githubusercontent.com/48930920/151018004-596470f7-fd71-4a49-b4c3-229809a97158.png">

**Comment by MaggieMaSS** [comment]
@IanKrieger  Thanks for the feedback! I'll go ahead to create a bug ticket to address this issue!

**Comment by MaggieMaSS** [comment]
@IanKrieger  Thanks for the feedback! We made the scroll component height dynamic. And instead of setting a fixed heigh, we set a fixed max-height. for better user experience.  

According to our chat on circulo channel, I'm going to create a feature request ticket for this issue. I'll discuss this with my teammates and the ideal solution would be user able to choose to use a custom height to  create a fixed component, or  choose to use dynamic height  component.
