### ISSUE TITLE
[BUG] filesystem.exist() and filesystem.dir() bug

### ISSUE THREAD

**Issue by alokmishra1** [open-olive/loop-development-kit#570]
**Describe the bug**
filesystem.exist() does not return true for a folder in shared location. filesystem.dir() gives error when correct directory path(shared path) is given.

for a shared location in package.json file
`{
            "value": "\\\\DESKTOP-76JGIBU\\**"
 },`
for a check whether a folder exist or not in shared location, it is returning false for a folder that exist.
`const logDirExists = await filesystem.exists("////DESKTOP-76JGIBU//Data");
 console.log('logDirExists============', logDirExists, " - ". "////DESKTOP-76JGIBU//Data");`

but for a file this function returns true
`const logDirExists = await filesystem.exists("////DESKTOP-76JGIBU//Data//Booking Reference New Data V3.xlsx");
 console.log('logDirExists============', logDirExists, " - ". "////DESKTOP-76JGIBU//Data//Booking Reference New Data V3.xlsx");`
**To Reproduce**
1. Go to 
check existance for a folder in shared location, it will return false. But for a file it returns true.
Also filesystem.dir() throws exception when a shared folder directory is passed as parameter.

**Expected behavior**
await filesystem.exists() should return true for a folder in shared location. Also filesystem.dir() should return result when a shared dir is passed.
**Screenshots**
![image](https://user-images.githubusercontent.com/72005525/165113547-3631b185-fe3a-4776-9e8d-d7111cc6ce2e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - LDK Version: latest
 - Olive Helps Version: 0.43.1

**Comment by iangallOlive** [comment]
Hi! Thanks for reporting this!

I could be mistaken, but I think the issue is that you're using too many slashes. When using backslashes, you need to escape them in strings. But when using forward slashes, you only need to use the exact amount.

So for your example, I think you should use **either** `"//DESKTOP-76JGIBU/Data/Booking Reference New Data V3.xlsx"` **or** `"\\\\DESKTOP-76JGIBU\\Data\\Booking Reference New Data V3.xlsx"`

Let me know if that fixes the issue, and if not, we can look into it more.
