### ISSUE TITLE
Form Input Select does not contain 'Value' configurable attribute.

### ISSUE THREAD

**Issue by advocatia** [open-olive/loop-development-kit#87]
Currently the Olive Helps LDK does not provide functionality for configuring a 'Value' attribute, unlike other Form Input types. 

```
["Text"] = new Text { Label = "TextInput", Tooltip = "Text tooltip.", Value ="TEXT VALUE", Order = 1 },
["State"] = new Select
{
    Label = "SelectInput",
    Tooltip = "Select tooltip.",
    Order = 2,
    Options = new[] { "Option 1", "Option 2" }
},
```
In this example, I am able to set the value of a Text Form Input to "TEXT VALUE" upon initializing a WhisperForm(), but unable to set a value attribute of a Select Form Input.

**Comment by cshields-oliveai** [comment]
Created new internal task for this. Status: In progress.

**Comment by cshields-oliveai** [comment]
@advocatia Due to the work completed as part of our transition to the Javascript-only model for the LDK, we have tweaked the function signatures slightly for some aptitudes. In the latest LDK version, you will find that both `Select` and `RadioGroup` now have `selected` attributes. Here are the new interfaces for reference:

Select:
```typescript
export declare type Select = WhisperComponent<WhisperComponentType.Select> & {
  label: string;
  options: string[];
  onSelect: (value: number) => void;
  selected?: number;
  tooltip?: string;
};
```

RadioGroup:
```typescript
export declare type RadioGroup = WhisperComponent<WhisperComponentType.RadioGroup> & {
  onSelect: (value: number) => void;
  options: string[];
  selected?: number;
};
```

We believe this attribute will accomplish the behavior you are looking for. Please let us know if you have any further issue with the the Select Whisper Type.

**Comment by cshields-oliveai** [comment]
@advocatia We are going to close this issue. If you are still experiencing a problem with these Whisper Components, please open another issue.

Thank you for taking the time to help improve the LDK!
